import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactQueryClientProvider } from "./provider";
import Navigation from "@/components/nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="ltr">
      <body className={inter.className}>
        <ReactQueryClientProvider>
          <header className="w-[100%] p-[1rem] bg-[#3a3a3a] flex items-center">
            <Navigation />
          </header>

          {children}
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
